# Generated by Django 3.1.7 on 2021-03-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=55)),
                ('short_name', models.CharField(max_length=55)),
                ('bquantity', models.IntegerField()),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('BT', 'BT'), ('CE', 'CE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mech.', 'Mech.')], max_length=15)),
                ('category', models.CharField(choices=[('Book', 'Book'), ('Journal', 'Journal'), ('Article', 'Article')], max_length=20)),
                ('date_access', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
