# Generated by Django 3.1.7 on 2021-03-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False)),
                ('jname', models.CharField(max_length=55)),
                ('jyear', models.IntegerField(max_length=5)),
            ],
        ),
    ]
